### ISSUE TITLE
Read `config.yaml` from XDG standard paths

### ISSUE THREAD

**Issue by erhhung** [kardolus/chatgpt-cli#30]
As more CLI apps are adopting the path conventions laid out by the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), it would be nice if `config.yaml` and other generated files like thread history are placed in these standard paths—or at least look for them in these paths before using `~/.chatgpt-cli/`:

- `config.yaml` — use `$XDG_CONFIG_HOME/chatgpt-cli/config.yaml` (if `XDG_CONFIG_HOME` is NOT explicitly defined, use `~/.config/chatgpt-cli/config.yaml`)
- `history/default.json` etc. — use `$XDG_DATA_HOME/chatgpt-cli/history/default.json` (if `XDG_DATA_HOME` is NOT explicitly defined, use `~/.local/share/chatgpt-cli/history/default.json`)

**Comment by kardolus** [comment]
Hi @erhhung, I think this makes a lot of sense. I did not know about the `XDG standard paths` concept when I created the CLI. 

It will take me a minute to implement this feature: I will need to create a migration script that moves your current config over to the appropriate directory. However, this migration should work from any version of the CLI (there is a migration script that runs already to account for an earlier change). So it's a little tricky :). 

There are also some complications around the case in which the directory does not exist. It seems like most other CLIs try to create the directory in that case.

**Comment by kardolus** [comment]
@erhhung I finally fixed this. It took me forever because I didn't see the simple solution until just now. I was going to migrate everyone over with a backwards compatible migration script. It would require a minor bump in the versioning and it would be tedious and so I kept pushing it forward.

Then I realized I could just make the config directory path configurable and have the users do it themselves :) 

So I did! 
* Commit: https://github.com/kardolus/chatgpt-cli/commit/918331699580829858b54a202b85aab0990d49f7
* Release: https://github.com/kardolus/chatgpt-cli/releases/tag/v1.6.7
