### ISSUE TITLE
Start a new conversation

### ISSUE THREAD

**Issue by andreaganduglia** [kardolus/chatgpt-cli#4]
Could be useful exclude history from context and/or have a way to start a new conversation. Something like: `chatgpt --new-chat`. 

I just learned in the hard way how can be painful kept a large context in a loop.

Thx

**Comment by kardolus** [comment]
Thanks for your feedback! I have been struggling with this myself as well.

As a coincidence I was just about to release `1.2.0` when I read this. 

In this release I introduced a three tier configuration strategy in which environment variables take precedence over a user provided `config.yaml`, which in turn takes precedence over default values. 

Long story short, you can now use `OPENAI_OMIT_HISTORY` (or update the `config.yaml`) in order to turn off any sort of history reading/writing. Example: 
```
OPENAI_OMIT_HISTORY=true cat big_file.txt | chatgpt give me the tldr
``` 
Just in case you were not aware yet, there's also the `--clear-history` flag which removes your local history.

Here's the documentation of the new configuration: https://github.com/kardolus/chatgpt-cli#configuration

Please let me know what you think!

**Comment by kardolus** [comment]
I'm also thinking about adding `chat_name` as a configuration option. In this way you can have per chat history like you do on the website.

**Comment by kardolus** [comment]
Just released `1.3.0` with support for per thread context :). Closing this issue for now. Please feel free to reopen or make a new one.

**Comment by acro5piano** [comment]
Let me share my experience.

I had an inverted issue. My issue was the chat history was not saved, meaning ChatGPT preserves any contents. The reason is that directory `$HOME/.chatgpt-cli` was missing for some reason.

```
$ chatgpt --clear-history

stat /home/kazuya/.chatgpt-cli: no such file or directory
```

Then I created the directory and my issue is gone.

```
mkdir $HOME/.chatgpt-cli
```

Hope this helps someone. Thank you for the great tool!

**Comment by kardolus** [comment]
Thanks @acro5piano! In the current version of the CLI (1.3.3), the directory should no longer be removed:
```
± |main ✓| →  chatgpt --clear-history
History successfully cleared.

± |main ✓| → stat $HOME/.chatgpt-cli
16777232 22380009 drwxr-xr-x 4 gkardolus staff 0 128 "Jul 10 15:47:17 2023" "Jul 10 15:32:56 2023" "Jul 10 15:32:56 2023" "May  4 02:49:41 2023" 4096 0 0 /Users/kardolus/.chatgpt-cli
```
Thanks for sharing your feedback!
