### ISSUE TITLE
403 not supported

### ISSUE THREAD

**Issue by gearonix** [kardolus/chatgpt-cli#44]
```
➜  $ chatgpt test                                                                                                                                                             ✭ ✱
http status 403: Country, region, or territory not supported
```

**Comment by kardolus** [comment]
Hi @gearonix, I was unaware that ChatGPT has country restrictions. Apparently it only works in supported countries: https://help.openai.com/en/articles/7947663-chatgpt-supported-countries

And not in these countries: 

Afghanistan
Bhutan
Central African Republic
Chad
Eritrea
Eswatini
Iran
Libya
North Korea
South Sudan
Sudan
Syria
Yemen
Russia
China
Cuba
Italy (temporarily banned due to GDPR compliance issues)
